"use client";
import { use } from "react";
import { useProfile } from "@/hooks/useProfile";
import CVSection from "@/components/CVSection";
import ReputationBadge from "@/components/ReputationBadge";

export default function CVPage({ params }) {
  const { wallet } = use(params);
  const { profile, loading } = useProfile(wallet);

  return (
    <div style={{ maxWidth:800, margin:"40px auto", padding:"0 24px",
      fontFamily:"Space Grotesk, sans-serif", color:"#f5f0e8" }}>
      <div style={{ display:"flex", justifyContent:"space-between",
        alignItems:"flex-start", marginBottom:32 }}>
        <div>
          <div style={{ fontFamily:"Archivo Black, sans-serif", fontSize:28,
            color:"#f5f0e8", marginBottom:4 }}>
            {wallet.slice(0,8)}...{wallet.slice(-6)}
          </div>
          <div style={{ fontFamily:"Space Mono, monospace", fontSize:11, color:"#555" }}>
            {wallet}
          </div>
        </div>
        <div style={{ textAlign:"right" }}>
          <ReputationBadge score={profile?.reputation?.score || 0} />
          <div style={{ fontFamily:"Space Mono, monospace", fontSize:10,
            color:"#555", marginTop:6 }}>
            ProofLedger Verified Profile
          </div>
        </div>
      </div>

      <CVSection title="Proof Summary" accent="#F7931A">
        <div style={{ display:"grid", gridTemplateColumns:"repeat(3,1fr)", gap:12 }}>
          {[["Documents", profile?.anchors||0],
            ["Attestations", profile?.attests||0],
            ["NFTs Minted", profile?.nfts||0]].map(([k,v]) => (
            <div key={k} style={{ border:"2px solid #222", padding:12, textAlign:"center" }}>
              <div style={{ fontFamily:"Archivo Black, sans-serif", fontSize:24,
                color:"#F7931A" }}>{v}</div>
              <div style={{ fontFamily:"Space Mono, monospace", fontSize:9,
                color:"#555", marginTop:4 }}>{k.toUpperCase()}</div>
            </div>
          ))}
        </div>
      </CVSection>

      <CVSection title="Blockchain Identity" accent="#38bdf8">
        <div style={{ fontFamily:"Space Mono, monospace", fontSize:11, color:"#888" }}>
          <div>Network: Stacks Mainnet (Bitcoin L2)</div>
          <div style={{ marginTop:6 }}>Address: {wallet}</div>
          <div style={{ marginTop:6 }}>
            <a href={`https://explorer.hiro.so/address/${wallet}`}
              target="_blank" rel="noreferrer"
              style={{ color:"#F7931A", textDecoration:"none" }}>
              View on Hiro Explorer ↗
            </a>
          </div>
        </div>
      </CVSection>

      <div style={{ marginTop:32, borderTop:"2px solid #1a1a1a", paddingTop:16,
        fontFamily:"Space Mono, monospace", fontSize:9, color:"#444", textAlign:"center" }}>
        Generated by ProofLedger · proofleger.vercel.app · All data is on-chain and verifiable
      </div>
    </div>
  );
}